"""Registry contracts in, the `ToolSpec`s a `ChatRequest` carries out. §5.1's "tool catalogue".

Stage 7.6. The only module that turns a contract into what the model sees, and what it produces
is exactly three things per tool: the name, the description and the input JSON schema. Not the
minimum role, not the delegated service, not the side effect, not the output schema — the model
needs none of them to call a tool correctly, and every one of them is information about this
server that a prompt injection could try to reason with.

**The catalogue is already authorized.** Callers pass the names the actor's role permits at the
resolved hotel (`ToolInvocationService.permitted_tools`), so the model is never offered a tool it
could not use and is never told why. Authorization stays in code; nothing about it is written into
the prompt. The invocation service re-checks every call anyway — a model that names a tool it was
not offered fails closed there.

**Deterministic.** Sorted by name, schemas generated by Pydantic from static classes, so the same
permitted set produces a byte-identical catalogue every time. A test pins that.
"""

from __future__ import annotations

from collections.abc import Iterable

from app.copilot.registry import ToolRegistry
from app.llm.base import ToolSpec


def build_catalogue(registry: ToolRegistry, permitted: Iterable[str]) -> tuple[ToolSpec, ...]:
    """The specs for *permitted*, sorted by name. A name the registry lacks is refused."""
    wanted = sorted(set(permitted))
    specs: list[ToolSpec] = []
    for name in wanted:
        contract = registry.get(name).contract
        specs.append(
            ToolSpec(
                name=contract.name,
                description=contract.description,
                input_schema=contract.input_schema(),
            )
        )
    return tuple(specs)


__all__ = ["build_catalogue"]
