import type { DateRange, DecimalString } from '@/types/analytics'

/**
 * The review contracts, transcribed from `app.schemas.review` and confirmed against the live
 * OpenAPI document and real requests.
 *
 * Six facts that check established, each of which shaped the UI:
 *
 * 1. **A review has no identifier of its own.** `reviews` carries no `public_id`, and the
 *    API says so explicitly. A review is addressed **through its booking** --
 *    `.../bookings/{booking_public_id}/review`, singular, because `uq_reviews_booking_id`
 *    makes it a singleton. `GET /hotels/{h}/reviews/1` is a 404.
 * 2. **A review without a booking therefore has no URL at all.** The schema permits one --
 *    that is how a review harvested from an external platform is stored when its reviewer
 *    cannot be matched to a guest -- and such a review appears in the hotel's list but
 *    **cannot be moderated**, because there is no address to send a PATCH to. The UI states
 *    this rather than showing a control that could not work.
 * 3. **There is no DELETE**, on either URL: 405, verified. `is_published` is the column the
 *    schema provides for taking a review down, and PATCH `{is_published: false}` is the
 *    withdrawal.
 * 4. **Two rating scales coexist in one list.** `rating_scale` is 5 or 10 -- Booking.com
 *    scores out of ten, TripAdvisor out of five -- and the seeded data really does contain
 *    both. Nothing in this application converts one to the other.
 * 5. **`rating_normalized` is generated by PostgreSQL** as `rating / rating_scale`, a
 *    fraction in [0, 1]. It is response-only: sending it is a 422, and the column is
 *    GENERATED ALWAYS, so a direct write is refused with SQLSTATE 428C9.
 * 6. **PATCH reaches two columns and no others.** `is_published` and `responded_at`.
 *    Sending `rating` or `body` is a 422 -- verified both -- because the guest's account of
 *    their stay is not something this API lets the hotel rewrite.
 */

/** Mirrors `ck_reviews_source_valid`. Seven values, and the list is closed. */
export type ReviewSource =
  | 'direct'
  | 'booking_com'
  | 'tripadvisor'
  | 'google'
  | 'expedia'
  | 'airbnb'
  | 'other'

/**
 * Mirrors `ck_reviews_rating_scale_valid`: 5 or 10.
 *
 * Typed as a union rather than `number` so a scale the schema does not have cannot be
 * constructed here. The server agrees: `rating_scale: 7` is a 422.
 */
export type RatingScale = 5 | 10

/** One review, as the API returns it. */
export interface Review {
  readonly hotel_public_id: string
  /**
   * The stay this review is of, when there is one.
   *
   * **Null means the review has no individual URL**, so it can be read in the list and
   * neither fetched alone nor moderated. See fact 2 in the module docstring.
   */
  readonly booking_public_id: string | null
  /** Null for a review whose reviewer was never matched to a guest record. */
  readonly guest_public_id: string | null
  readonly source: ReviewSource
  /** The external platform's own identifier, for imported reviews. */
  readonly external_review_id: string | null
  /** `NUMERIC(4,2)` on the wire as a string, on the scale in `rating_scale`. */
  readonly rating: DecimalString
  /** 5 or 10. Read together with `rating` or neither means anything. */
  readonly rating_scale: number
  /** GENERATED `rating / rating_scale`, a fraction in [0, 1]. Never computed here. */
  readonly rating_normalized: DecimalString
  readonly title: string | null
  /** Nullable: rating-only reviews are common, and the seeded data is full of them. */
  readonly body: string | null
  /** Two lower-case letters, or null. `ck_reviews_language_format`. */
  readonly language: string | null
  /** The display name on the review, which need not be the guest's own name. */
  readonly reviewer_name: string | null
  readonly review_date: string
  readonly is_published: boolean
  /** When the hotel marked the review answered. Null when it has not. */
  readonly responded_at: string | null
  readonly created_at: string
  readonly updated_at: string
}

/**
 * `POST /hotels/{h}/bookings/{b}/review` -- the `ReviewCreate` payload.
 *
 * The author is **not** in the payload: `guest_id` is derived from the booking, and the
 * schema's own reason is that accepting it would create a way to attribute a review to
 * someone who did not stay. Sending `guest_public_id` is a 422, verified.
 */
export interface ReviewCreateRequest {
  readonly source: ReviewSource
  readonly rating: DecimalString
  readonly rating_scale: RatingScale
  readonly review_date: string
  readonly external_review_id?: string
  readonly title?: string
  readonly body?: string
  readonly language?: string
  readonly reviewer_name?: string
  /** The table defaults to true; accepted so an import can land a review already hidden. */
  readonly is_published?: boolean
}

/**
 * `PATCH /hotels/{h}/bookings/{b}/review` -- the `ReviewModerationUpdate` payload.
 *
 * Both fields optional: an omitted field is left untouched, and an **explicit null** clears
 * the column, which is how a response is retracted. That distinction is why `responded_at`
 * is typed `string | null` rather than being made optional-only -- the two mean different
 * things on the wire and both are used.
 */
export interface ReviewModerationRequest {
  readonly is_published?: boolean
  readonly responded_at?: string | null
}

/** One fifth of the normalized scale, as the analytics layer buckets it. */
export interface RatingBucket {
  /** 1..5. Bucket n covers (n-1)/5 <= rating_normalized <= n/5, upper bound exclusive
   * except in bucket 5. */
  readonly bucket: number
  readonly lower_bound: DecimalString
  readonly upper_bound: DecimalString
  readonly count: number
}

/** One channel's share of the reviews in the range. */
export interface ReviewSourceBreakdown {
  /** Typed as a plain string, not `ReviewSource`: this is a value the server groups by, and
   * a code added to the backend later must render rather than crash the page. */
  readonly source: string
  readonly review_count: number
  readonly published_count: number
  readonly average_rating_normalized: DecimalString | null
}

/**
 * `GET /hotels/{h}/analytics/reviews` -- **the only source of review statistics** in this
 * application.
 *
 * Counts, the published count, the average and the distribution are all computed by
 * PostgreSQL over `reviews.review_date`. Both date bounds are required; omitting either is a
 * 422, verified. Reviews with no guest and no booking are included, because excluding them
 * would silently drop every review harvested from an external platform.
 */
export interface ReviewAnalyticsResponse {
  readonly hotel_public_id: string
  readonly range: DateRange
  readonly totals: {
    readonly review_count: number
    readonly published_count: number
    /** AVG(rating_normalized) as a fraction, or null when the range holds no reviews. */
    readonly average_rating_normalized: DecimalString | null
  }
  readonly rating_distribution: readonly RatingBucket[]
  readonly by_source: readonly ReviewSourceBreakdown[]
}
